# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a005bc5704b838b79475089be6584b61e88ad7febf4742f14931dbdf364341327540d2d59520f9aa7f20adc1f09ed3aba908b3049e955a280888c06a7ae5f2

test:
  secret_key_base: e31508d09f10b3644794a065b011d4e8cb044db852213640778337472ed03b04ce1b406d3bc1451d37e15c629bd9315cfcb38045e7f7e4a022d0c28fec9a6243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
